---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-10.04
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: debian-6.0.10
  - name: debian-7.7
  - name: centos-5.11
  - name: centos-6.6
  - name: centos-7.0
  - name: fedora-19
  - name: fedora-20

suites:
  - name: default
    run_list:
      - recipe[limits_test_cookbook]
    provisioner:
      client_rb:
        node_name: 'limits-test-node'
